name: Keepalive Test
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly

jobs:
  main-job:
    name: Main Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run:  echo hi
  keepalive-job:
    name: Keepalive Workflow
    needs: main-job
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v4
      - name: Test Keepalive
        uses: gautamkrishnar/keepalive-workflow@v1
        with:
          use_api: true
          time_elapsed: 0

